<template>
    <v-card>
        <v-card-text>
            <div class="tw-flex w-full  tw-justify-end text-b">
                Privacy Policy
            </div>
            <div class="tw-flex w-full tw-justify-end">
                Date of last update: July 1, 2020
            </div>
            <br>

            <p class="paragraph-css">
                The following privacy policy (“Privacy Policy”) describes how Tracsia and its affiliates (collectively,
                “Tracsia”, “we” or “us”) collects, uses and discloses information you provide to us or which we
                otherwise collect in providing products or services to you (“User Information”).
            </p>
            <p class="paragraph-css">
                Use of our products and services (collectively “Tracsia Products”) is subject to the terms of our Terms
                of Use (the “Terms”) and any other written agreement we enter into with you. The provisions of this
                Privacy Policy are incorporated into each such agreement as if fully set forth therein.
            </p>
            <br />
            <p class="text-b">Online or Offline Interactions with Tracsia</p>
            <p class="paragraph-css">When you interact online or offline with us, we may receive User Information from
                you, including Personal Data. This may happen when you a) visit our websites, b) access the Tracsia
                Platform, b) download materials from our websites, c) provide account information through our websites,
                or d) attend events we host or sponsor. We also may collect information about you from sources such as
                public databases, marketing partners, social media sources, event hosts and partners when you interact
                with them. We or others acting on our behalf may collect such information, including information
                relating to you (“Personal Data”), through such interactions. Categories of Personal Data we may collect
                include your name, email address, physical address, your employer, your job title, payment details for
                payment for our services, your phone number, your IP address, and your user name. Personal Data may be
                collected by us when you enter Personal Data on our website forms. IP addresses are collected by us on
                an automated basis when you use our websites. We may be able to determine your location from your IP
                address. For additional information on our use of cookies and similar technologies, please review our
                Cookies Policy at www.Tracsia.com
            </p>
            <p class="paragraph-css">We use the information we collect from such interactions to provide Tracsia
                Products to you in accordance with our Terms, to satisfy legal requirements that apply to us, or to meet
                our legitimate business interests, as further described below. In particular, we use User Information
                to: </p>
            <ul>
                <li>Deliver Tracsia Products to you.</li>
                <li>Respond to requests for information from you.</li>
                <li>Develop, maintain and improve Tracsia Products we provide to you, including website services.</li>
                <li>Provide you with an account for access to our websites and Tracsia Products, and manage your
                    account.</li>
                <li>Provide administrative information to you.</li>
                <li>Deliver marketing-related communications to you.</li>
                <li>Invite you to participate in surveys or related studies.</li>
                <li>Diagnose, analyze or monitor security, security threats or technical issues or problems relating to
                    our websites or Tracsia Products.</li>
                <li>Comply with applicable laws, rules, regulations, legal or regulatory proceedings or to protect our
                    legal rights.</li>
                <li>Engage in other courses of action disclosed to you in connection with use of Tracsia Products from
                    time to time.</li>

            </ul>
            <p class="paragraph-css">If we process your Personal Data for purposes other than those set forth above, we
                will inform you prior to such processing.</p>
            <br>

            <br />
            <p class="text-b">Opting Out of Marketing Communications</p>
            <p class="paragraph-css">If you wish not to receive marketing-related emails from us, please email us to
                that effect at <span class="text-g"> info@Tracsia.com</span>
            </p>
            <br />
            <p class="text-b">Operational Data</p>
            <p class="paragraph-css">Operational Data is information generated by your use of Tracsia Products such as
                page views, interactions, number of active and licensed users, errors, number of searches, source types
                and format (e.g., xml, json, csv, etc.), app workflows, etc. We use Operational Data to provide and
                enhance Tracsia Products. For example, we may use this data to analyze, monitor and troubleshoot
                operational issues; analyze and monitor behavior across deployments; perform data analysis; provide
                recommendations to help optimize usage; monitor and understand performance issues; improve the operation
                of Tracsia Products; personalize your experience; and build new functionality and features.
            </p>
            <p class="paragraph-css">Collection Practices in Connection with Administrative and Operational Activities
            </p>
            <p class="paragraph-css">Tracsia also collects your Personal Data to carry out various obligations in
                connection with provision of Tracsia Products to you, such as entering your name, email address,
                physical address, your employer, your job title, your phone number, and your user name into our customer
                database systems and manage your account and maintaining our billing and payments, customer services and
                support services activities and updating software.</p>
            <br />
            <p class="text-b">Sharing of User Information</p>
            <p class="paragraph-css">We may share User Information with third parties as follows:
            </p>
            <ul>
                <li>We may disclose User Information to our affiliates who are subject to this Privacy Policy for the
                    purpose of helping them deliver or administer Tracsia Products.</li>
                <li>We may disclose User Information to our service providers (e.g., infrastructure as a service,
                    professional/customer/support services), pursuant to written agreements with confidentiality
                    obligations.</li>
                <li>We may disclose User Information to our business partners or event sponsors pursuant to written
                    agreements with confidentiality obligations.</li>
                <li>We may disclose User Information as we deem necessary or appropriate under applicable laws, rules or
                    regulations (including laws, rules or regulations outside your country of residence), in order to
                    comply with laws, rules or regulations, to respond to requests from any governmental or public
                    authority (including outside your country of residence), to enforce provisions of any agreement
                    between you and us, to protect our operations, or to protect our rights, privacy, safety or property
                    and/or that of you or others.</li>
                <li>We may disclose User Information in connection with a proposed or actual merger, sale, joint
                    venture, reorganization, assignment, transfer or other disposition or similar corporate transaction
                    relating to all or any portion of our business, assets or capital stock.</li>

            </ul>
            <br />
            <p class="text-b">How We Secure User Information</p>
            <p class="paragraph-css">We take reasonable technical and organizational measures to safeguard Personal Data
                against theft, loss and unauthorized access, disclosure, misuse, destruction or alteration. Nonetheless,
                no data transmission, software, or storage system can be guaranteed to be 100% secure and we cannot
                guarantee absolute security. In addition, we are not responsible for the security of data or information
                you transmit to us over networks that are not under our control. If you have reason to believe that your
                interaction with us is no longer secure, please notify us immediately in accordance with the “Questions
                and Comments” section below. If we determine a breach of our systems has occurred, we may notify you or
                others consistent with applicable laws and/or as agreed in our agreements with you. We may communicate
                with you electronically regarding security, privacy, and administrative issues relating to your use of
                Tracsia Products and the information you provide to us.
            </p>
            <br />
            <p class="text-b">Retention; Transfers</p>
            <p class="paragraph-css">We retain User Information for the period we determine is necessary to carry out
                the purposes set forth in this Privacy Policy, except where a longer retention period may be required or
                not prohibited under applicable law. We retain contract information for the duration of your contract
                with us and afterward as required or permitted under applicable law. Your Personal Data may be stored
                and/or processed in any country in which we have facilities or in which we engage service providers
                which are located outside of your country of residence. Different data protection rules from those
                applicable in your country of residence may therefore apply.</p>
            <br />
            <p class="text-b">Third Parties</p>
            <p class="paragraph-css">Tracsia Products may include links to or facilitate access to other websites or
                online services. This Privacy Policy does not address, and we are not responsible for, the privacy,
                information, or practices of other parties, including any app developer, app provider, social media
                platform provider, operating system provider, wireless service provider, or device manufacturer. The
                inclusion of a link in Tracsia Products does not imply endorsement of the linked site or service by us.
                We encourage you to review the privacy policies and learn about the privacy practices of those companies
                whose websites you choose to visit.</p>
            <br />
            <p class="text-b">Changes</p>
            <p class="paragraph-css">We may modify this Privacy Policy from time to time and our updates will be posted
                here.
            </p>
            <br />
            <p class="text-b">
                Questions or Comments
            </p>
            <p class="paragraph-css">If you have questions, comments or concerns regarding this Privacy Policy, you can
                contact us any time at <span class="text-g"> info@Tracsia.com</span> .</p>
            <!-- <br/>
            <p class="text-b"></p>
            <p class="paragraph-css"></p>
            <br/>
            <p class="text-b"></p>
            <p class="paragraph-css"></p>
            <br/>
            <p class="text-b"></p>
            <p class="paragraph-css"></p>
            <br/><p class="text-b"></p>
            <p class="paragraph-css"></p>
            <br/> -->

        </v-card-text>
    </v-card>
</template>

<script>
export default {

}
</script>

<style lang="scss" scoped>
.paragraph-css {
    text-indent: 8px;
    word-break: break-all;
}

.text-g {
    color: #26e661;
    font-weight: 400
}

.text-b {
    font-weight: 700;
    color: black;
}
</style>